"""
Milvus collection schema for books multimodal collection.

Dataset: https://zenodo.org/records/4265096
Embedding model: CLIP ViT-B/32 (clip-ViT-B-32 via sentence-transformers)
"""

from pymilvus import DataType, MilvusClient

from config import BOOKS_COVER_EMBEDDING_DIM, BOOKS_DESCRIPTION_EMBEDDING_DIM, BOOKS_NLIST

BOOKS_OUTPUT_FIELDS = [
    "id",
    "goodreads_id",
    "isbn",
    "title",
    "author",
    "description",
    "language",
    "coverImg",
    "publisher",
    "pages",
    "has_image",
]


def books_schema(client: MilvusClient):
    """
    Full schema for the books collection.

    Scalar fields    — Metadata used for filtering, display, and faceting.
    text_embedding   — CLIP encoding of the productDisplayName field.
    image_embedding  — CLIP encoding of the product photograph.
    has_image        — False when an image was unavailable during ingestion.
    """
    schema = client.create_schema(
        auto_id=True,
        enable_dynamic_fields=False,
        description=(
            "Books collection with multimodal retrieval support. "
            "Uses the following vectors: "
            " - MiniLM dense vectors for descriptions (CLIP ViT-B/32, 512-dim, COSINE),"
            " - CLIP dense vectors for covers (CLIP ViT-B/32, 512-dim, COSINE)."
            "Supports: text-semantic, image-similarity, text-to-image, and image-to-text searches."
        ),
    )

    # Scalar metadata
    schema.add_field("id", DataType.INT64, is_primary=True, description="Primary key automatically generated by Milvus")
    schema.add_field("goodreads_id", DataType.VARCHAR, max_length=64, description="Stripped numerical ID from the dataset")
    schema.add_field("isbn", DataType.VARCHAR, max_length=32, description="Book's ISBN from the dataset")
    schema.add_field("title", DataType.VARCHAR, max_length=512, description="Title of the book from the dataset")
    schema.add_field("author", DataType.VARCHAR, max_length=256, description="Book's author name from the dataset")
    schema.add_field("description", DataType.VARCHAR, max_length=6000, description="Book's description from the dataset - text used to build the text_embedding")
    schema.add_field("language", DataType.VARCHAR, max_length=32, description="Book's language from the dataset")
    schema.add_field("coverImg", DataType.VARCHAR, max_length=2048, description="Book's URL cover image URL from the dataset")
    schema.add_field("publisher", DataType.VARCHAR, max_length=256, description="Book's publisher from the dataset")
    schema.add_field("pages", DataType.INT32, description="Book's number of pages from the dataset")
    schema.add_field("has_image", DataType.BOOL, description="True when image_embedding encodes an actual book's cover image")

    # Vector fields
    schema.add_field(
        "description_embedding",
        DataType.FLOAT_VECTOR,
        dim=BOOKS_DESCRIPTION_EMBEDDING_DIM,
        description="CLIP text encoding from description (512-dim)"
    )
    schema.add_field(
        "cover_embedding",
        DataType.FLOAT_VECTOR,
        dim=BOOKS_COVER_EMBEDDING_DIM,
        description="CLIP image encoding from book's cover image (512-dim)"
    )

    return schema


def books_index_params(client: MilvusClient):
    """
    Index parameters for the books collection.

    Scalar indexes — INVERTED for efficient WHERE filtering.
    Vector indexes — IVF_FLAT with COSINE; one index per vector field.
    """
    idx = client.prepare_index_params()

    # Scalar indexes
    idx.add_index("goodreads_id", index_type="INVERTED")
    idx.add_index("isbn", index_type="INVERTED")
    idx.add_index("author", index_type="INVERTED")
    idx.add_index("language", index_type="INVERTED")
    idx.add_index("publisher", index_type="INVERTED")
    idx.add_index("pages", index_type="INVERTED")
    idx.add_index("has_image", index_type="INVERTED")

    # Dense vector indexes (required)

    # description_embedding 
    idx.add_index(
        field_name="description_embedding",
        index_type="IVF_FLAT",
        index_name="description_embedding_index",
        metric_type="COSINE",
        params={"nlist": BOOKS_NLIST},
    )

    # cover_embedding 
    idx.add_index(
        field_name="cover_embedding",
        index_type="IVF_FLAT",
        index_name="cover_embedding_index",
        metric_type="COSINE",
        params={"nlist": BOOKS_NLIST},
    )

    return idx