"""
Milvus collection schema for reviews (Hybrid Search: Dense + Sparse).

This schema implements BM25 full-text search alongside semantic dense embeddings.

Dataset: https://cseweb.ucsd.edu/~jmcauley/datasets/goodreads.html
"""

from pymilvus import DataType, Function, FunctionType, MilvusClient

from config import REVIEWS_BM25_ANALYZER_LANGUAGE, REVIEWS_EMBEDDING_DIM, REVIEWS_NLIST

REVIEWS_OUTPUT_FIELDS = [
    "id",
    "review_id",
    "book_id",
    "isbn",
    "language",
    "rating",
    "n_votes",
    "date_added",
    "review_text",
]


def reviews_schema(client: MilvusClient):
    """
    Full schema for the reviews collection.

    Scalar fields    — Metadata used for filtering, display, and faceting.
    review_embedding — MiniLM-L6-v2 encoding of the review_text
    sparse_bm25      — BM25 Sparse encoding of the review_text 
    """
    schema = client.create_schema(
        auto_id=True,
        enable_dynamic_fields=False,
        description=(
            "Reviews collection with hybrid retrieval support. "
            "Uses MiniLM dense vectors and BM25 sparse vectors generated from review_text."
        ),
    )

    # Scalar metadata
    schema.add_field("id", DataType.INT64, is_primary=True, description="Primary key automatically generated by Milvus")
    schema.add_field("review_id", DataType.VARCHAR, max_length=64, description="Review's ID from the dataset")
    schema.add_field("book_id", DataType.VARCHAR, max_length=64, description="Book's numerical ID from the dataset")
    schema.add_field("isbn", DataType.VARCHAR, max_length=32, description="Book's ISBN found using merging with the book dataset")
    schema.add_field("language", DataType.VARCHAR, max_length=32, description="Review's language from the dataset")
    schema.add_field("rating", DataType.INT32, description="Review's rating for the book from the dataset")
    schema.add_field("n_votes", DataType.INT32, description="Review's number of likes from the dataset")
    schema.add_field("date_added", DataType.INT64, description="Review's date of addition from the dataset")
    
    # --- Text Field with Full-Text Search (Analyzer) Enabled ---
    schema.add_field(
        "review_text",
        DataType.VARCHAR,
        max_length=6000,
        enable_analyzer=True,
        analyzer_params={"type": REVIEWS_BM25_ANALYZER_LANGUAGE},
        enable_match=True,
        description="Review's text from the dataset"
    )

    # Vector fields
    # Dense embedding (e.g., MiniLM-L6-v2, 384-dim) for semantic similarity
    schema.add_field("review_embedding", DataType.FLOAT_VECTOR, dim=REVIEWS_EMBEDDING_DIM)

    # Sparse vector (BM25) — auto-populated from review_text via the Function below
    schema.add_field("sparse_bm25", DataType.SPARSE_FLOAT_VECTOR, is_function_output=True)

    # BM25 sparse vector auto-population, it automatically converts review_text into sparse vectors during ingestion
    schema.add_function(
        Function(
            name="bm25_reviews",
            function_type=FunctionType.BM25,
            input_field_names=["review_text"],
            output_field_names=["sparse_bm25"],
        )
    )

    return schema


def reviews_index_params(client: MilvusClient):
    """
    Index parameters for the reviews collection.

    Scalar indexes        — INVERTED for efficient WHERE filtering.
    Dense vector indexes  — IVF_FLAT with COSINE; one index per vector field.
    Sparse vector indexes — SPARSE_INVERTED_INDEX with BM25; one index per vector field.
    """
    idx = client.prepare_index_params()

    # Scalar indexes
    idx.add_index("review_id", index_type="INVERTED")
    idx.add_index("book_id", index_type="INVERTED")
    idx.add_index("isbn", index_type="INVERTED")
    idx.add_index("language", index_type="INVERTED")
    idx.add_index("rating", index_type="INVERTED")
    idx.add_index("n_votes", index_type="INVERTED")
    idx.add_index("date_added", index_type="INVERTED")

    # Dense vector index (required)
    idx.add_index(
        "review_embedding",
        index_type="IVF_FLAT",
        index_name="review_embedding_index",
        metric_type="COSINE",
        params={"nlist": REVIEWS_NLIST},
    )

    # Sparse vector index for traditional keyword/BM25 retrieval (required)
    idx.add_index(
        "sparse_bm25",
        index_type="SPARSE_INVERTED_INDEX",
        index_name="sparse_bm25_index",
        metric_type="BM25",
    )

    return idx