-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-16 17:43:41 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Administrator 
    ( 
     id_korisnika INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Administrator 
    ADD CONSTRAINT Administrator_PK PRIMARY KEY ( id_korisnika ) ;

CREATE TABLE Adresa 
    ( 
     id_adrese             INTEGER  NOT NULL , 
     broj_adrese           VARCHAR2 (16)  NOT NULL , 
     mesto_adrese          VARCHAR2 (64)  NOT NULL , 
     poštanski_broj_adrese INTEGER  NOT NULL , 
     ulica_adrese          VARCHAR2 (64)  NOT NULL , 
     opština_adrese        VARCHAR2 (64) 
    ) 
;

ALTER TABLE Adresa 
    ADD CONSTRAINT Adresa_PK PRIMARY KEY ( id_adrese ) ;

CREATE TABLE Autor 
    ( 
     datum_smrti_autora   DATE , 
     datum_rođenja_autora DATE , 
     biografija_autora    CLOB , 
     putanja_slike_autora VARCHAR2 (256) , 
     naziv_autora         VARCHAR2 (128)  NOT NULL , 
     id_autora            INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Autor 
    ADD CONSTRAINT Autor_PK PRIMARY KEY ( id_autora ) ;

CREATE TABLE Biblioteka 
    ( 
     id_biblioteke         INTEGER  NOT NULL , 
     naziv_biblioteke      VARCHAR2 (64)  NOT NULL , 
     žiro_račun_biblioteke VARCHAR2 (64)  NOT NULL , 
     Adresa_id_adrese      INTEGER  NOT NULL , 
     Menadžer_id_korisnika INTEGER 
    ) 
;
CREATE UNIQUE INDEX Biblioteka__IDX ON Biblioteka 
    ( 
     Menadžer_id_korisnika ASC 
    ) 
;

ALTER TABLE Biblioteka 
    ADD CONSTRAINT Biblioteka_PK PRIMARY KEY ( id_biblioteke ) ;

CREATE TABLE Bibliotekar 
    ( 
     id_korisnika             INTEGER  NOT NULL , 
     Biblioteka_id_biblioteke INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Bibliotekar 
    ADD CONSTRAINT Bibliotekar_PK PRIMARY KEY ( id_korisnika ) ;

CREATE TABLE Čet_Poruka 
    ( 
     putanja_slike_uz_čet_poruku  VARCHAR2 (256) , 
     id_čet_poruke                INTEGER  NOT NULL , 
     tip_čet_poruke               VARCHAR2 (16)  NOT NULL , 
     datum_kreiranja_čet_poruke   DATE  NOT NULL , 
     sadržaj_čet_poruke           CLOB  NOT NULL , 
     izvori_čet_poruke            JSON , 
     Čet_Sesija_id_čet_sesije     INTEGER  NOT NULL , 
     Član_Biblioteke_id_korisnika INTEGER  NOT NULL , 
     datum_ocene_čet_poruke       DATE , 
     ocena_čet_poruke             NUMBER , 
     komentar_čet_poruke          CLOB 
    ) 
;

ALTER TABLE Čet_Poruka 
    ADD 
    CHECK (tip_čet_poruke IN ('Asistent', 'Član_Biblioteke')) 
;

ALTER TABLE Čet_Poruka 
    ADD 
    CHECK (ocena_čet_poruke IN (1, 2, 3, 4, 5)) 
;

ALTER TABLE Čet_Poruka 
    ADD CONSTRAINT Čet_Poruka_PK PRIMARY KEY ( id_čet_poruke, Čet_Sesija_id_čet_sesije ) ;

CREATE TABLE Čet_Sesija 
    ( 
     id_čet_sesije                 INTEGER  NOT NULL , 
     naslov_čet_sesije             VARCHAR2 (256)  NOT NULL , 
     datum_kreiranja_čet_sesije    DATE  NOT NULL , 
     datum_aktivnosti_čet_sesije   DATE  NOT NULL , 
     sažetak_akitvnosti_čet_sesije CLOB , 
     arhivirana_čet_sesija         NUMBER  NOT NULL , 
     obrisana_čet_sesija           NUMBER  NOT NULL , 
     id_korisnika                  INTEGER  NOT NULL , 
     Član_Biblioteke_id_korisnika  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Čet_Sesija 
    ADD CONSTRAINT Čet_Sesija_PK PRIMARY KEY ( id_čet_sesije ) ;

CREATE TABLE čita 
    ( 
     Član_Biblioteke_id_korisnika INTEGER  NOT NULL , 
     "e-Knjiga_id_eknjige"        INTEGER  NOT NULL , 
     "e-Knjiga_id_knjige"         INTEGER  NOT NULL , 
     datum_početka_čitanja        DATE , 
     datum_poslednjeg_čitanja     DATE , 
     trenutna_strana_čitanja      INTEGER , 
     datum_završetka_čitanja      DATE , 
     status_čitanja               VARCHAR2 (16) 
    ) 
;

ALTER TABLE čita 
    ADD 
    CHECK (status_čitanja IN ('Napušteno', 'U toku', 'Završeno')) 
;

ALTER TABLE čita 
    ADD CONSTRAINT čita_PK PRIMARY KEY ( Član_Biblioteke_id_korisnika, "e-Knjiga_id_eknjige", "e-Knjiga_id_knjige" ) ;

CREATE TABLE Član_Biblioteke 
    ( 
     id_korisnika INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Član_Biblioteke 
    ADD CONSTRAINT Član_Biblioteke_PK PRIMARY KEY ( id_korisnika ) ;

CREATE TABLE "e-Knjiga" 
    ( 
     id_eknjige              INTEGER  NOT NULL , 
     putanja_eknjige         VARCHAR2 (256)  NOT NULL , 
     datum_dodavanja_eknjige DATE  NOT NULL , 
     format_eknjige          VARCHAR2 (16)  NOT NULL , 
     broj_strana_eknjige     INTEGER  NOT NULL , 
     Knjiga_id_knjige        INTEGER  NOT NULL 
    ) 
;

ALTER TABLE "e-Knjiga" 
    ADD 
    CHECK (format_eknjige IN ('EPUB-No images', 'EPUB-Older', 'EPUB3')) 
;

ALTER TABLE "e-Knjiga" 
    ADD CONSTRAINT "e-Knjiga_PK" PRIMARY KEY ( id_eknjige, Knjiga_id_knjige ) ;

CREATE TABLE je_napisao 
    ( 
     Knjiga_id_knjige INTEGER  NOT NULL , 
     Autor_id_autora  INTEGER  NOT NULL , 
     uloga_autora     VARCHAR2 (64) 
    ) 
;

ALTER TABLE je_napisao 
    ADD CONSTRAINT je_napisao_PK PRIMARY KEY ( Knjiga_id_knjige, Autor_id_autora ) ;

CREATE TABLE Katalog 
    ( 
     id_kataloga              INTEGER  NOT NULL , 
     naziv_kataloga           VARCHAR2 (64)  NOT NULL , 
     standard_kataloga        VARCHAR2 (16)  NOT NULL , 
     obrisan_katalog          NUMBER  NOT NULL , 
     Biblioteka_id_biblioteke INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Katalog 
    ADD 
    CHECK (standard_kataloga IN ('Dublin Core', 'MARC', 'RDA')) 
;

ALTER TABLE Katalog 
    ADD CONSTRAINT Katalog_PK PRIMARY KEY ( id_kataloga ) ;

CREATE TABLE Knjiga 
    ( 
     id_knjige               INTEGER  NOT NULL , 
     putanja_naslovne_knjige VARCHAR2 (256) , 
     obrisana_knjiga         NUMBER  NOT NULL , 
     isbn13_knjige           VARCHAR2 (20) , 
     naslov_knjige           VARCHAR2 (128)  NOT NULL , 
     sinopsis_knjige         CLOB  NOT NULL 
    ) 
;

ALTER TABLE Knjiga 
    ADD CONSTRAINT Knjiga_PK PRIMARY KEY ( id_knjige ) ;

CREATE TABLE Korisnik 
    ( 
     id_korisnika               INTEGER  NOT NULL , 
     ime_korisnika              VARCHAR2 (32)  NOT NULL , 
     prezime_korisnika          VARCHAR2 (32)  NOT NULL , 
     putanja_profilne_korisnika VARCHAR2 (256) , 
     uloga_korisnika            VARCHAR2 (16)  NOT NULL , 
     datum_rođenja_korisnika    DATE , 
     šifra_korisnika            VARCHAR2 (256)  NOT NULL , 
     email_korisnika            VARCHAR2 (256)  NOT NULL , 
     broj_telefona_korisnika    VARCHAR2 (16) , 
     Adresa_id_adrese           INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Korisnik 
    ADD CONSTRAINT CH_INH_Korisnik 
    CHECK (uloga_korisnika IN ('Administrator', 'Bibliotekar', 'Menadžer', 'Član_Biblioteke')) 
;

ALTER TABLE Korisnik 
    ADD CONSTRAINT Korisnik_PK PRIMARY KEY ( id_korisnika ) ;

CREATE TABLE lajkuje 
    ( 
     Član_Biblioteke_id_korisnika INTEGER  NOT NULL , 
     Recenzija_id_knjige          INTEGER  NOT NULL , 
     Recenzija_id_korisnika       INTEGER  NOT NULL 
    ) 
;

ALTER TABLE lajkuje 
    ADD CONSTRAINT lajkuje_PK PRIMARY KEY ( Član_Biblioteke_id_korisnika, Recenzija_id_knjige, Recenzija_id_korisnika ) ;

CREATE TABLE Menadžer 
    ( 
     id_korisnika             INTEGER  NOT NULL , 
     Biblioteka_id_biblioteke INTEGER 
    ) 
;
CREATE UNIQUE INDEX Menadžer__IDX ON Menadžer 
    ( 
     Biblioteka_id_biblioteke ASC 
    ) 
;

ALTER TABLE Menadžer 
    ADD CONSTRAINT Menadžer_PK PRIMARY KEY ( id_korisnika ) ;

CREATE TABLE Odgovor 
    ( 
     id_odgovora                  INTEGER  NOT NULL , 
     tekst_odgovora               CLOB  NOT NULL , 
     datum_kreiranja_odgovora     DATE  NOT NULL , 
     Recenzija_id_knjige          INTEGER  NOT NULL , 
     Recenzija_id_korisnika       INTEGER  NOT NULL , 
     Član_Biblioteke_id_korisnika INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Odgovor 
    ADD CONSTRAINT Odgovor_PK PRIMARY KEY ( id_odgovora, Recenzija_id_knjige, Recenzija_id_korisnika ) ;

CREATE TABLE Pozajmica 
    ( 
     id_pozajmice                 INTEGER  NOT NULL , 
     datum_očekivanog_vraćanja    DATE  NOT NULL , 
     datum_vraćanja_pozajmice     DATE , 
     datum_pozajmice              DATE  NOT NULL , 
     status_pozajmice             VARCHAR2 (16) , 
     Rezervacija_id_rezervacije   INTEGER , 
     Član_Biblioteke_id_korisnika INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Pozajmica 
    ADD 
    CHECK (status_pozajmice IN ('Aktivna', 'Izgubljena', 'Prekoračenje', 'Vraćena')) 
;
CREATE UNIQUE INDEX Pozajmica__IDX ON Pozajmica 
    ( 
     Rezervacija_id_rezervacije ASC 
    ) 
;

ALTER TABLE Pozajmica 
    ADD CONSTRAINT Pozajmica_PK PRIMARY KEY ( id_pozajmice ) ;

CREATE TABLE Primerak_Knjige 
    ( 
     id_primerka_knjige             INTEGER  NOT NULL , 
     godina_izdanja_primerka_knjige INTEGER  NOT NULL , 
     Knjiga_id_knjige               INTEGER  NOT NULL , 
     Katalog_id_kataloga            INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Primerak_Knjige 
    ADD CONSTRAINT Primerak_Knjige_PK PRIMARY KEY ( id_primerka_knjige, godina_izdanja_primerka_knjige, Knjiga_id_knjige ) ;

CREATE TABLE Produženje_Pozajmice 
    ( 
     id_produžetka               INTEGER  NOT NULL , 
     status_produžetka           VARCHAR2 (16)  NOT NULL , 
     kanal_produžetka            VARCHAR2 (16)  NOT NULL , 
     datum_obrade_produžetka     DATE , 
     datum_produžetka            DATE  NOT NULL , 
     novi_datum_vraćanja         DATE , 
     stari_datum_vraćanja        DATE , 
     razlog_odbijanja_produžetka VARCHAR2 (256) , 
     Pozajmica_id_pozajmice      INTEGER  NOT NULL , 
     Bibliotekar_id_korisnika    INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Produženje_Pozajmice 
    ADD 
    CHECK (status_produžetka IN ('Odbijen', 'Odobren', 'U obradi')) 
;

ALTER TABLE Produženje_Pozajmice 
    ADD 
    CHECK (kanal_produžetka IN ('Biblioteka', 'Onlajn')) 
;

ALTER TABLE Produženje_Pozajmice 
    ADD CONSTRAINT Produženje_Pozajmice_PK PRIMARY KEY ( id_produžetka, Pozajmica_id_pozajmice ) ;

CREATE TABLE Recenzija 
    ( 
     datum_početka_čitanja        DATE , 
     datum_završetka_čitanja      DATE , 
     datum_ažuriranja_recenzije   TIMESTAMP , 
     ocena_knjige_uz_recenziju    NUMBER , 
     datum_kreiranja_recenzije    TIMESTAMP  NOT NULL , 
     tekst_recenzije              CLOB  NOT NULL , 
     Knjiga_id_knjige             INTEGER  NOT NULL , 
     Član_Biblioteke_id_korisnika INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Recenzija 
    ADD 
    CHECK (ocena_knjige_uz_recenziju IN (1, 2, 3, 4, 5)) 
;

ALTER TABLE Recenzija 
    ADD CONSTRAINT Recenzija_PK PRIMARY KEY ( Knjiga_id_knjige, Član_Biblioteke_id_korisnika ) ;

CREATE TABLE Rezervacija 
    ( 
     id_rezervacije                 INTEGER  NOT NULL , 
     status_rezervacije             VARCHAR2 (16)  NOT NULL , 
     datum_rezervacije              DATE  NOT NULL , 
     rok_kupljenja_rezervacije      DATE , 
     procena_ispunjenja_rezervacije DATE , 
     stvarno_ispunjenje_rezervacije DATE , 
     kanal_rezervacije              VARCHAR2 (16)  NOT NULL , 
     Pozajmica_id_pozajmice         INTEGER , 
     Knjiga_id_knjige               INTEGER  NOT NULL , 
     Biblioteka_id_biblioteke       INTEGER  NOT NULL , 
     Član_Biblioteke_id_korisnika   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Rezervacija 
    ADD 
    CHECK (status_rezervacije IN ('Aktivna', 'Ispunjena', 'Odbijena', 'Poništena', 'Spremna')) 
;

ALTER TABLE Rezervacija 
    ADD 
    CHECK (kanal_rezervacije IN ('Biblioteka', 'Onlajn')) 
;
CREATE UNIQUE INDEX Rezervacija__IDX ON Rezervacija 
    ( 
     Pozajmica_id_pozajmice ASC 
    ) 
;

ALTER TABLE Rezervacija 
    ADD CONSTRAINT Rezervacija_PK PRIMARY KEY ( id_rezervacije ) ;

CREATE TABLE spada_u 
    ( 
     Knjiga_id_knjige INTEGER  NOT NULL , 
     Žanr_id_žanra    INTEGER  NOT NULL 
    ) 
;

ALTER TABLE spada_u 
    ADD CONSTRAINT spada_u_PK PRIMARY KEY ( Knjiga_id_knjige, Žanr_id_žanra ) ;

CREATE TABLE upravlja 
    ( 
     Bibliotekar_id_korisnika INTEGER  NOT NULL , 
     Katalog_id_kataloga      INTEGER  NOT NULL 
    ) 
;

ALTER TABLE upravlja 
    ADD CONSTRAINT upravlja_PK PRIMARY KEY ( Bibliotekar_id_korisnika, Katalog_id_kataloga ) ;

CREATE TABLE Žanr 
    ( 
     id_žanra    INTEGER  NOT NULL , 
     naziv_žanra VARCHAR2 (64)  NOT NULL 
    ) 
;

ALTER TABLE Žanr 
    ADD CONSTRAINT Žanr_PK PRIMARY KEY ( id_žanra ) ;

ALTER TABLE Administrator 
    ADD CONSTRAINT Administrator_Korisnik_FK FOREIGN KEY 
    ( 
     id_korisnika
    ) 
    REFERENCES Korisnik 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Biblioteka 
    ADD CONSTRAINT Biblioteka_Adresa_FK FOREIGN KEY 
    ( 
     Adresa_id_adrese
    ) 
    REFERENCES Adresa 
    ( 
     id_adrese
    ) 
;

ALTER TABLE Biblioteka 
    ADD CONSTRAINT Biblioteka_Menadžer_FK FOREIGN KEY 
    ( 
     Menadžer_id_korisnika
    ) 
    REFERENCES Menadžer 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Bibliotekar 
    ADD CONSTRAINT Bibliotekar_Biblioteka_FK FOREIGN KEY 
    ( 
     Biblioteka_id_biblioteke
    ) 
    REFERENCES Biblioteka 
    ( 
     id_biblioteke
    ) 
;

ALTER TABLE Bibliotekar 
    ADD CONSTRAINT Bibliotekar_Korisnik_FK FOREIGN KEY 
    ( 
     id_korisnika
    ) 
    REFERENCES Korisnik 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Čet_Poruka 
    ADD CONSTRAINT Čet_Poruka_Čet_Sesija_FK FOREIGN KEY 
    ( 
     Čet_Sesija_id_čet_sesije
    ) 
    REFERENCES Čet_Sesija 
    ( 
     id_čet_sesije
    ) 
;

ALTER TABLE Čet_Poruka 
    ADD CONSTRAINT Čet_Poruka_Član_Biblioteke_FK FOREIGN KEY 
    ( 
     Član_Biblioteke_id_korisnika
    ) 
    REFERENCES Član_Biblioteke 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Čet_Sesija 
    ADD CONSTRAINT Čet_Sesija_Član_Biblioteke_FK FOREIGN KEY 
    ( 
     Član_Biblioteke_id_korisnika
    ) 
    REFERENCES Član_Biblioteke 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE čita 
    ADD CONSTRAINT čita_Član_Biblioteke_FK FOREIGN KEY 
    ( 
     Član_Biblioteke_id_korisnika
    ) 
    REFERENCES Član_Biblioteke 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE čita 
    ADD CONSTRAINT "čita_e-Knjiga_FK" FOREIGN KEY 
    ( 
     "e-Knjiga_id_eknjige",
     "e-Knjiga_id_knjige"
    ) 
    REFERENCES "e-Knjiga" 
    ( 
     id_eknjige,
     Knjiga_id_knjige
    ) 
;

ALTER TABLE Član_Biblioteke 
    ADD CONSTRAINT Član_Biblioteke_Korisnik_FK FOREIGN KEY 
    ( 
     id_korisnika
    ) 
    REFERENCES Korisnik 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE "e-Knjiga" 
    ADD CONSTRAINT "e-Knjiga_Knjiga_FK" FOREIGN KEY 
    ( 
     Knjiga_id_knjige
    ) 
    REFERENCES Knjiga 
    ( 
     id_knjige
    ) 
;

ALTER TABLE je_napisao 
    ADD CONSTRAINT je_napisao_Autor_FK FOREIGN KEY 
    ( 
     Autor_id_autora
    ) 
    REFERENCES Autor 
    ( 
     id_autora
    ) 
;

ALTER TABLE je_napisao 
    ADD CONSTRAINT je_napisao_Knjiga_FK FOREIGN KEY 
    ( 
     Knjiga_id_knjige
    ) 
    REFERENCES Knjiga 
    ( 
     id_knjige
    ) 
;

ALTER TABLE Katalog 
    ADD CONSTRAINT Katalog_Biblioteka_FK FOREIGN KEY 
    ( 
     Biblioteka_id_biblioteke
    ) 
    REFERENCES Biblioteka 
    ( 
     id_biblioteke
    ) 
;

ALTER TABLE Korisnik 
    ADD CONSTRAINT Korisnik_Adresa_FK FOREIGN KEY 
    ( 
     Adresa_id_adrese
    ) 
    REFERENCES Adresa 
    ( 
     id_adrese
    ) 
;

ALTER TABLE lajkuje 
    ADD CONSTRAINT lajkuje_Član_Biblioteke_FK FOREIGN KEY 
    ( 
     Član_Biblioteke_id_korisnika
    ) 
    REFERENCES Član_Biblioteke 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE lajkuje 
    ADD CONSTRAINT lajkuje_Recenzija_FK FOREIGN KEY 
    ( 
     Recenzija_id_knjige,
     Recenzija_id_korisnika
    ) 
    REFERENCES Recenzija 
    ( 
     Knjiga_id_knjige,
     Član_Biblioteke_id_korisnika
    ) 
;

ALTER TABLE Menadžer 
    ADD CONSTRAINT Menadžer_Biblioteka_FK FOREIGN KEY 
    ( 
     Biblioteka_id_biblioteke
    ) 
    REFERENCES Biblioteka 
    ( 
     id_biblioteke
    ) 
;

ALTER TABLE Menadžer 
    ADD CONSTRAINT Menadžer_Korisnik_FK FOREIGN KEY 
    ( 
     id_korisnika
    ) 
    REFERENCES Korisnik 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Odgovor 
    ADD CONSTRAINT Odgovor_Član_Biblioteke_FK FOREIGN KEY 
    ( 
     Član_Biblioteke_id_korisnika
    ) 
    REFERENCES Član_Biblioteke 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Odgovor 
    ADD CONSTRAINT Odgovor_Recenzija_FK FOREIGN KEY 
    ( 
     Recenzija_id_knjige,
     Recenzija_id_korisnika
    ) 
    REFERENCES Recenzija 
    ( 
     Knjiga_id_knjige,
     Član_Biblioteke_id_korisnika
    ) 
;

ALTER TABLE Pozajmica 
    ADD CONSTRAINT Pozajmica_Član_Biblioteke_FK FOREIGN KEY 
    ( 
     Član_Biblioteke_id_korisnika
    ) 
    REFERENCES Član_Biblioteke 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Pozajmica 
    ADD CONSTRAINT Pozajmica_Rezervacija_FK FOREIGN KEY 
    ( 
     Rezervacija_id_rezervacije
    ) 
    REFERENCES Rezervacija 
    ( 
     id_rezervacije
    ) 
;

ALTER TABLE Produženje_Pozajmice 
    ADD CONSTRAINT PP_Bibliotekar_FK FOREIGN KEY 
    ( 
     Bibliotekar_id_korisnika
    ) 
    REFERENCES Bibliotekar 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Produženje_Pozajmice 
    ADD CONSTRAINT PP_Pozajmica_FK FOREIGN KEY 
    ( 
     Pozajmica_id_pozajmice
    ) 
    REFERENCES Pozajmica 
    ( 
     id_pozajmice
    ) 
;

ALTER TABLE Primerak_Knjige 
    ADD CONSTRAINT Primerak_Knjige_Katalog_FK FOREIGN KEY 
    ( 
     Katalog_id_kataloga
    ) 
    REFERENCES Katalog 
    ( 
     id_kataloga
    ) 
;

ALTER TABLE Primerak_Knjige 
    ADD CONSTRAINT Primerak_Knjige_Knjiga_FK FOREIGN KEY 
    ( 
     Knjiga_id_knjige
    ) 
    REFERENCES Knjiga 
    ( 
     id_knjige
    ) 
;

ALTER TABLE Recenzija 
    ADD CONSTRAINT Recenzija_Član_Biblioteke_FK FOREIGN KEY 
    ( 
     Član_Biblioteke_id_korisnika
    ) 
    REFERENCES Član_Biblioteke 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Recenzija 
    ADD CONSTRAINT Recenzija_Knjiga_FK FOREIGN KEY 
    ( 
     Knjiga_id_knjige
    ) 
    REFERENCES Knjiga 
    ( 
     id_knjige
    ) 
;

ALTER TABLE Rezervacija 
    ADD CONSTRAINT Rezervacija_Biblioteka_FK FOREIGN KEY 
    ( 
     Biblioteka_id_biblioteke
    ) 
    REFERENCES Biblioteka 
    ( 
     id_biblioteke
    ) 
;

ALTER TABLE Rezervacija 
    ADD CONSTRAINT Rezervacija_Član_Biblioteke_FK FOREIGN KEY 
    ( 
     Član_Biblioteke_id_korisnika
    ) 
    REFERENCES Član_Biblioteke 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE Rezervacija 
    ADD CONSTRAINT Rezervacija_Knjiga_FK FOREIGN KEY 
    ( 
     Knjiga_id_knjige
    ) 
    REFERENCES Knjiga 
    ( 
     id_knjige
    ) 
;

ALTER TABLE Rezervacija 
    ADD CONSTRAINT Rezervacija_Pozajmica_FK FOREIGN KEY 
    ( 
     Pozajmica_id_pozajmice
    ) 
    REFERENCES Pozajmica 
    ( 
     id_pozajmice
    ) 
;

ALTER TABLE spada_u 
    ADD CONSTRAINT spada_u_Knjiga_FK FOREIGN KEY 
    ( 
     Knjiga_id_knjige
    ) 
    REFERENCES Knjiga 
    ( 
     id_knjige
    ) 
;

ALTER TABLE spada_u 
    ADD CONSTRAINT spada_u_Žanr_FK FOREIGN KEY 
    ( 
     Žanr_id_žanra
    ) 
    REFERENCES Žanr 
    ( 
     id_žanra
    ) 
;

ALTER TABLE upravlja 
    ADD CONSTRAINT upravlja_Bibliotekar_FK FOREIGN KEY 
    ( 
     Bibliotekar_id_korisnika
    ) 
    REFERENCES Bibliotekar 
    ( 
     id_korisnika
    ) 
;

ALTER TABLE upravlja 
    ADD CONSTRAINT upravlja_Katalog_FK FOREIGN KEY 
    ( 
     Katalog_id_kataloga
    ) 
    REFERENCES Katalog 
    ( 
     id_kataloga
    ) 
;

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Administrator 
BEFORE INSERT OR UPDATE OF id_korisnika 
ON Administrator 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (16); 
BEGIN 
    SELECT A.uloga_korisnika INTO d 
    FROM Korisnik A 
    WHERE A.id_korisnika = :new.id_korisnika; 
    IF (d IS NULL OR d <> 'Administrator') THEN 
        raise_application_error(-20223,'FK Administrator_Korisnik_FK in Table Administrator violates Arc constraint on Table Korisnik - discriminator column uloga_korisnika doesn''t have value ''Administrator'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Bibliotekar 
BEFORE INSERT OR UPDATE OF id_korisnika 
ON Bibliotekar 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (16); 
BEGIN 
    SELECT A.uloga_korisnika INTO d 
    FROM Korisnik A 
    WHERE A.id_korisnika = :new.id_korisnika; 
    IF (d IS NULL OR d <> 'Bibliotekar') THEN 
        raise_application_error(-20223,'FK Bibliotekar_Korisnik_FK in Table Bibliotekar violates Arc constraint on Table Korisnik - discriminator column uloga_korisnika doesn''t have value ''Bibliotekar'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Menadžer 
BEFORE INSERT OR UPDATE OF id_korisnika 
ON Menadžer 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (16); 
BEGIN 
    SELECT A.uloga_korisnika INTO d 
    FROM Korisnik A 
    WHERE A.id_korisnika = :new.id_korisnika; 
    IF (d IS NULL OR d <> 'Menadžer') THEN 
        raise_application_error(-20223,'FK Menadžer_Korisnik_FK in Table Menadžer violates Arc constraint on Table Korisnik - discriminator column uloga_korisnika doesn''t have value ''Menadžer'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Član_Biblioteke 
BEFORE INSERT OR UPDATE OF id_korisnika 
ON Član_Biblioteke 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (16); 
BEGIN 
    SELECT A.uloga_korisnika INTO d 
    FROM Korisnik A 
    WHERE A.id_korisnika = :new.id_korisnika; 
    IF (d IS NULL OR d <> 'Član_Biblioteke') THEN 
        raise_application_error(-20223,'FK Član_Biblioteke_Korisnik_FK in Table Član_Biblioteke violates Arc constraint on Table Korisnik - discriminator column uloga_korisnika doesn''t have value ''Član_Biblioteke'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            25
-- CREATE INDEX                             4
-- ALTER TABLE                             75
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
